version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8510:8510"
    #environment:
    #  - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    container_name: yt_langgraph
    restart: always
