version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8510:8510"
    volumes:
      - .:/app:rw
    container_name: yt_langgraph
    restart: always
    environment:
      - PYTHONPATH=/app
    user: "1000:1000"
